### ISSUE TITLE
AttributeError: module 'numpy' has no attribute '_no_nep50_warning' when importing TensorFlow Federated

### ISSUE THREAD

**Issue by arunrajvakathanam** [google-parfait/tensorflow-federated#4367]
Description:

While trying to use TensorFlow Federated (TFF), I encountered an AttributeError upon importing the tensorflow_federated module. The error message specifically states:

AttributeError: module 'numpy' has no attribute '_no_nep50_warning'
Environment:

Python version: Python 3.10.12

Steps to reproduce:

Run the following Python code:
Python
import tensorflow_federated as tff
Use code with caution. [Learn more](https://bard.google.com/faq#coding)
Observe the AttributeError message.
Expected behavior:

Importing tensorflow_federated should not cause any errors.

Actual behavior:

The AttributeError message indicates an unexpected internal issue within NumPy, potentially preventing proper initialization of TensorFlow Federated.

source code https://github.com/tensorflow/federated/blob/v0.66.0/docs/tutorials/federated_learning_for_image_classification.ipynb

**Comment by GiuliaFContardi** [comment]
Same problem for the same source code.

Using the link for **Google Colab** I got:
CODE1:
`!pip install --quiet --upgrade tensorflow-federated`
OUPUT_ERROR:
`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
lida 0.0.10 requires fastapi, which is not installed.
lida 0.0.10 requires kaleido, which is not installed.
lida 0.0.10 requires python-multipart, which is not installed.
lida 0.0.10 requires uvicorn, which is not installed.
flax 0.7.5 requires jax>=0.4.19, but you have jax 0.4.14 which is incompatible.
google-colab 1.0.0 requires portpicker==1.5.2, but you have portpicker 1.6.0 which is incompatible.
ipython-sql 0.5.0 requires sqlalchemy>=2.0, but you have sqlalchemy 1.4.20 which is incompatible.`

CODE2:
`import collections
import numpy as np
import tensorflow as tf
import tensorflow_federated as tff  #<---- generate error
np.random.seed(0)
tff.federated_computation(lambda: 'Hello, World!')()`
OUTPUT_ERROR:
**`AttributeError: module 'numpy' has no attribute '_no_nep50_warning'`**

I tried to solve it installing the required packages hoping better results, but I kept getting version conflicts from many packages.

**Comment by AlirezaSalehy** [comment]
Same issue, how did you fix that?

**Comment by boxer-code** [comment]
Any updates? I'm facing the same issue.

**Comment by arunrajvakathanam** [comment]
Currently I can't get a solution if I get a solution I will let you know

**Comment by atmadeep** [comment]
Commenting in case a solution is available. Facing the same issue with ``numpy==1.24.4``

**Comment by michaelreneer** [comment]
Sorry for coming in late. The problem you are likely seeing is that the runtime you are using in colab has an older version of numpy or an older version of TFF. Some solutions...

1. Create your own runtime with only TFF and it's dependencies.
2. Uninstall the conflicting dependencies and install the correct ones.
3. You can try installing the new ones over top of the old ones.

**Comment by MarouaneMja** [comment]
For me it works with numpy=1.24.3

**Comment by michaelreneer** [comment]
TFF has a dependency on `numpy~=1.25` (See https://github.com/google-parfait/tensorflow-federated/blob/main/pyproject.toml#L44) and has been since [`v0.64.0`](https://github.com/google-parfait/tensorflow-federated/blob/v0.64.0/tensorflow_federated/tools/python_package/setup.py).

I suspect you are pulling in an older version of TFF. Can you run pip freeze and determine which version of TFF you are pulling in? I would recommend uninstalling all conflicting dependencies from the colab notebook.
